.TH swayimg 1 "August 2020" "swayimg" "User Commands"
.SH NAME
swayimg \- image viewer for Sway
.SH SYNOPSIS
swayimg [\fIOPTIONS\fR...] \fIFILE...\fR
.SH DESCRIPTION
The \fBswayimg\fR utility can be used for preview images inside the currently
focused window (container).
.PP
Use '-' as \fIFILE\fR to read image data from stdin.
.PP
The program uses Sway IPC to determine the geometry of the currently focused
workspace and window.
This data is used calculate the position and size of a new window.
Then the program adds two rules to the Sway: "floating enable" and
"move position" for \fBswayimg\fR application, creates a new Wayland window and
draws an image from the specified file.
.
.SH OPTIONS
.PP
.IP "\fB\-h\fR, \fB\-\-help\fR"
Display help message.
.IP "\fB\-v\fR, \fB\-\-version\fR"
Display version information and list of supported image formats.
.IP "\fB\-g\fR, \fB\-\-geometry\fR\fB=\fR\fIX,Y,WIDTH,HEIGHT\fR"
Set the absolute position and size of the window, for example
\fI10,20,100,200\fR creates a window at position 10x20 (top left corner) with
a size of 100x200. If this parameter is not specified, the geometry of the
currently focused window will be used.
.IP "\fB\-f\fR, \fB\-\-fullscreen\fR"
Start in full screen mode.
.IP "\fB\-s\fR, \fB\-\-scale\fR\fB=\fR\fISCALE\fR"
Set initial scale of the image. \fISCALE\fR can be a named value or absolute value in
percent. \'default\': reduce the image to fit the window, but do not enlarge it.
\'fit\': reduce or enlarge the image to fit the window.
.IP "\fB\-i\fR, \fB\-\-info\fR"
Show image properties on startup (path, size, current scale etc).
.
.SH KEYBINDINGS
.IP "\fBArrows\fR and vim-like moving keys (\fBh\fR,\fBj\fR,\fBk\fR,\fBl\fR)"
Move the view point.
.IP "\fB+\fP, \fB=\fR"
Zoom in.
.IP "\fB-\fP"
Zoom out.
.IP "\fBBackspace\fP"
Reset scale to defaults.
.IP "\fB0\fP"
Set scale to 100%.
.IP "\fB[\fP, \fB]\fP"
Rotate image.
.IP "\fBi\fP"
Show/hide image properties.
.IP "\fBf\fP, \fBF11\fP"
Toggle full screen mode.
.IP "\fBPgDown\fR, \fBSpace\fR, \fBn\fR"
Show next file.
.IP "\fBPgUp\fR, \fBp\fR"
Show previous file.
.IP "\fBEsc\fP, \fBEnter\fP, \fBF10\fP, \fBq\fP"
Exit the program.
.
.SH ENVIRONMENT
.PP
.IP \fISWAYSOCK\fR
Path to the socket file used for Sway IPC.
.
.SH NOTES
For suggestions, comments, bug reports etc. visit https://github.com/artemsen/swayimg
.SH AUTHOR
Artem Senichev <artemsen@gmail.com>
.
