.\" Swayimg: image viewer for Sway/Wayland
.\" Copyright (C) 2021 Artem Senichev <artemsen@gmail.com>
.TH SWAYIMG 1 2021-12-28 swayimg "Swayimg manual"
.SH NAME
swayimg \- image viewer for Sway
.SH SYNOPSIS
swayimg [\fIOPTIONS\fR...] \fIFILE...\fR
.SH DESCRIPTION
The \fBswayimg\fR utility can be used for preview images inside the currently
focused window (container).
.PP
Use '-' as \fIFILE\fR to read image data from stdin.
.PP
The program uses Sway IPC to determine the geometry of the currently focused
workspace and window.
This data is used calculate the position and size of a new window.
Then the program adds two rules to the Sway: "floating enable" and
"move position" for \fBswayimg\fR application, creates a new Wayland window and
draws an image from the specified file.
.\" options
.SH OPTIONS
.IP "\fB\-h\fR, \fB\-\-help\fR"
Display help message.
.IP "\fB\-v\fR, \fB\-\-version\fR"
Display version information and list of supported image formats.
.IP "\fB\-g\fR, \fB\-\-geometry\fR\fB=\fR\fIX,Y,WIDTH,HEIGHT\fR"
Set the absolute position and size of the window, for example
\fI10,20,100,200\fR creates a window at position 10x20 (top left corner) with
a size of 100x200. The comma can be replaced with any non-numeric character.
If this parameter is not specified, the geometry of the currently focused Sway
window will be used.
.IP "\fB\-b\fR, \fB\-\-background\fR\fB=\fR\fIXXXXXX\fR"
Set background color from RGB hex string, for example \fI1a2b3c\fR. If this
parameter is not specified or contains special value \fIgrid\fR, the default
grid background will be used.
.IP "\fB\-f\fR, \fB\-\-fullscreen\fR"
Start in full screen mode.
.IP "\fB\-s\fR, \fB\-\-scale\fR\fB=\fR\fISCALE\fR"
Set the default scale of the image. \fISCALE\fR is one of the named values.
\'default\': reduce the image to fit the window, but do not enlarge it.
\'fit\': reduce or enlarge the image to fit the window.
\'real\': real image size (100%).
.IP "\fB\-i\fR, \fB\-\-info\fR"
Show image properties on startup (path, size, current scale etc).
.\" keys
.SH KEYBINDINGS
.IP "\fBArrows\fR and vim-like moving keys (\fBh\fR,\fBj\fR,\fBk\fR,\fBl\fR)"
Move the view point.
.IP "\fB+\fP, \fB=\fR"
Zoom in.
.IP "\fB-\fP"
Zoom out.
.IP "\fB0\fP"
Set scale to 100%.
.IP "\fBBackspace\fP"
Reset scale to defaults.
.IP "\fBF5\fP, \fB[\fP"
Rotate 90 degrees anticlockwise.
.IP "\fBF6\fP, \fB]\fP"
Rotate 90 degrees clockwise.
.IP "\fBF7\fP"
Flip vertical.
.IP "\fBF8\fP"
Flip horizontal.
.IP "\fBi\fP"
Show/hide image properties.
.IP "\fBf\fP, \fBF11\fP"
Toggle full screen mode.
.IP "\fBPgDown\fR, \fBSpace\fR, \fBn\fR"
Show next file.
.IP "\fBPgUp\fR, \fBp\fR"
Show previous file.
.IP "\fBEsc\fP, \fBEnter\fP, \fBF10\fP, \fBq\fP"
Exit the program.
.SH ENVIRONMENT
.IP \fISWAYSOCK\fR
Path to the socket file used for Sway IPC.
.\" link to homepage
.SH BUGS
For suggestions, comments, bug reports etc. visit the
.UR https://github.com/artemsen/swayimg
project homepage
.UE .
