.\" Swayimg configuration file format.
.\" Copyright (C) 2022 Artem Senichev <artemsen@gmail.com>
.TH SWAYIMGRC 5 2022-02-09 swayimg "Swayimg configuration"
.SH "NAME"
swayimgrc \- configuration file for the Swayimg viewer
.SH "SYNOPSIS"
The Swayimg configuration file is a text-based INI file used to override the
default settings.
.\" ****************************************************************************
.\" Config file location
.\" ****************************************************************************
.SH "LOCATION"
Swayimg searches for a config file in the following locations, in this order:
.nf
\- $XDG_CONFIG_HOME/swayimg/config
\- $HOME/.config/swayimg/config
\- $XDG_CONFIG_DIRS/swayimg/config
\- /etc/xdg/swayimg/config
.\" ****************************************************************************
.\" Format description
.\" ****************************************************************************
.SH "DESCRIPTION"
The structure of the INI file consists of key-value pairs for properties and
sections that organize properties.
.PP
The basic element contained in the INI file is the key or property.
Every key has a name and a value, delimited by an equals sign (=).
.PP
The name appears to the left of the equals sign. The value can contain any
characters.
.PP
Keys are grouped into named sections. The section name appears on a line by
itself, in square brackets ([ and ]). All keys after the section declaration
are associated with that section.
.PP
The number sign (#) at the beginning of the line indicates a comment.
Empty lines and comments are ignored.
.PP
Any option can be overridden using the \fI--config\fR argument in the command
line, for instance: `swayimg --config="general.mode=gallery"`.
.\" ****************************************************************************
.\" General config section
.\" ****************************************************************************
.SH "SECTIONS"
.SS "General"
The general configuration is stored in the section \fB[general]\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBmode\fR = \fI[viewer|gallery]\fR"
Mode used at startup, \fIviewer\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBposition\fR = \fI[parent|X,Y]\fR"
Set initial position of the window (Sway only):
.nf
\fIparent\fR: set position from parent (currently active) window (default);
\fIX,Y\fR: absolute coordinates of the top left corner, e.g. 100,200.
.\" ----------------------------------------------------------------------------
.IP "\fBsize\fR = \fI[fullscreen|parent|image|W,H]\fR"
Set initial size of the window:
.nf
\fIfullscreen\fR: use fullscreen mode;
\fIparent\fR: set size from parent (currently active) window (Sway only, default);
\fIimage\fR: set size from the first loaded image;
\fIW,H\fR: absolute size of the window in pixels.
.\" ----------------------------------------------------------------------------
.IP "\fBdecoration\fR\fR = \fI[yes|no]\fR"
Use window decoration (borders and title), \fIno\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBsigusr1\fR = \fIACTION\fR"
Set the action to be performed when the SIGUSR1 signal is triggered.
Default value is \fIreload\fR.
.IP "\fBsigusr2\fR = \fIACTION\fR"
Set the action to be performed when the SIGUSR2 signal is triggered.
Default value is \fInext_file\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBapp_id\fR = \fINAME\fR"
Application ID used as window class name.
.\" ****************************************************************************
.\" Viewer config section
.\" ****************************************************************************
.SS "Viewer"
Configuration is defined in the \fB[viewer]\fR section.
.\" ----------------------------------------------------------------------------
.IP "\fBwindow\fR = \fI#COLOR\fR"
Window background color in RGB or RGBA format, default is \fI#00000000\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBtransparency\fR = \fI[grid|#COLOR]\fR"
Background for transparent images:
.nf
\fIgrid\fR: draw chessboard (default);
\fI#COLOR\fR: solid color in RGB or RGBA, e.g "#10ff4280".
.\" ----------------------------------------------------------------------------
.IP "\fBscale\fR = \fIMODE\fR"
Default image scale, valid modes are:
.nf
\fIoptimal\fR: 100% or less to fit to window (default);
\fIwidth\fR: fit image width to window width;
\fIheight\fR: fit image height to window height;
\fIfit\fR: fit to window;
\fIfill\fR: crop image to fill the window;
\fIreal\fR: real size (100%).
.\" ----------------------------------------------------------------------------
.IP "\fBkeep_zoom\fR\fR = \fI[yes|no]\fR"
Keep absolute zoom across images, \fIno\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBposition\fR = \fIPOSITION\fR"
Initial image position, valid modes are:
.nf
\fItop\fR: move image to top and center by width;
\fIcenter\fR: center by width and height (default);
\fIbottom\fR: move to bottom and center by width;
\fIleft\fR: move to left and center by height;
\fIright\fR: move to right and center by height;
\fItopleft\fR: move to top and left;
\fItopright\fR: move to top and right;
\fIbottomleft\fR: move to bottom and left;
\fIbottomright\fR: move to bottom and right.
.\" ----------------------------------------------------------------------------
.IP "\fBfixed\fR = \fI[yes|no]\fR"
Fix position of the image on the window surface, \fIyes\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBantialiasing\fR = \fIMETHOD\fR"
Scale method to use when anti-aliasing is enabled, valid choices are:
.nf
\fInearest\fR: nearest-neighbor, equivalent to antialiasing = no;
\fIbox\fR: nearest-neighbor on upscale, average in a box on downscale;
\fIbilinear\fR: bilinear;
\fIbicubic\fR: bicubic with the Catmull-Rom spline;
\fImks13\fR: Magic Kernel with the 2013 Sharp approximation (default);
.nf
In general, the methods improve in quality and decrease in performance from top to bottom.
.\" ----------------------------------------------------------------------------
.IP "\fBslideshow\fR = \fI[yes|no]\fR"
Run slideshow at startup, \fIno\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBslideshow_time\fR = \fISECONDS\fR"
Set slideshow image duration in seconds, default is \fI3\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBhistory\fR = \fISIZE\fR"
Number of previously viewed images to store in cache, \fI1\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBpreload\fR = \fISIZE\fR"
Number of images to preload in a separate thread, \fI1\fR by default.
.\" ****************************************************************************
.\" Gallery config section
.\" ****************************************************************************
.SS "Gallery"
Configuration is defined in the \fB[gallery]\fR section.
.\" ----------------------------------------------------------------------------
.IP "\fBsize\fR = \fIPIXELS\fR"
Size of the thumbnail in pixels, \fI200\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBpstore\fR = \fI[yes|no]\fR"
Enable/disable storing thumbnails in persistent storage, \fIno\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBfill\fR = \fI[yes|no]\fR"
Fill the entire tile with thumbnail, \fIyes\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBcache\fR = \fISIZE\fR"
Max number of thumbnails in cache, \fI0\fR for unlimited, \fI100\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBantialiasing\fR = \fIMETHOD\fR"
Scale method to use when anti-aliasing is enabled, valid choices are:
.nf
\fInearest\fR: nearest-neighbor, equivalent to antialiasing = no;
\fIbox\fR: nearest-neighbor on upscale, average in a box on downscale;
\fIbilinear\fR: bilinear;
\fIbicubic\fR: bicubic with the Catmull-Rom spline;
\fImks13\fR: Magic Kernel with the 2013 Sharp approximation (default);
.nf
In general, the methods improve in quality and decrease in performance from top to bottom.
.\" ----------------------------------------------------------------------------
.IP "\fBwindow\fR = \fI#COLOR\fR"
Background color of the window, default is \fI#00000000\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBbackground\fR = \fI#COLOR\fR"
Background color of the tile, default is \fI#202020ff\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBborder\fR = \fI#COLOR\fR"
Border color of the selected tile, default is \fI#000000ff\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBshadow\fR = \fI#COLOR\fR"
Shadow color of the selected tile, default is \fI#000000ff\fR.
.\" ****************************************************************************
.\" Image list config section
.\" ****************************************************************************
.SS "Image list"
The image list configuration is stored in the section \fB[list]\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBorder\fR = \fIORDER\fR"
Set order of the image list:
.nf
\fInone\fR: unsorted, order is system depended;
\fIalpha\fR: sorted alphabetically (default);
\fImtime\fR: sorted by file modification time;
\fIsize\fR: sorted by file size;
\fIrandom\fR: randomize list.
.\" ----------------------------------------------------------------------------
.IP "\fBreverse\fR\fR = \fI[yes|no]\fR"
Reverse sort order, \fIno\fR by default. 
.\" ----------------------------------------------------------------------------
.IP "\fBloop\fR\fR = \fI[yes|no]\fR"
Looping file list mode, \fIyes\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBrecursive\fR = \fI[yes|no]\fR"
Read directories recursively, \fIno\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBall\fR = \fI[yes|no]\fR"
Open all files in the directory of the specified file, \fIno\fR by default.
.\" ****************************************************************************
.\" Font config section
.\" ****************************************************************************
.SS "Font"
The font configuration is stored in the section \fB[font]\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBname\fR\fR = \fINAME\fR"
Set the font name used for text, default is \fImonospace\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBsize\fR = \fISIZE\fR"
Set the font size (in pt), default is \fI14\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBcolor\fR = \fI#COLOR\fR"
Set text color in RGBA format, default is \fI#ccccccff\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBbackground\fR = \fI#COLOR\fR"
Text background color, default is \fI#00000000\fR (none).
.\" ----------------------------------------------------------------------------
.IP "\fBshadow\fR = \fI#COLOR\fR"
Draw text shadow with specified color, default is \fI#000000d0\fR.
To disable shadow use fully transparent color \fI#00000000\fR.
.\" ****************************************************************************
.\" Text info config section
.\" ****************************************************************************
.SS "Text info: common configuration"
The section \fB[info]\fR describes how to display image meta data (file name,
size, EXIF etc).
.\" ----------------------------------------------------------------------------
.IP "\fBshow\fR = \fI[yes|no]\fR"
Enable or disable info text at startup, \fIyes\fR by default.
.\" ----------------------------------------------------------------------------
.IP "\fBinfo_timeout\fR = \fISECONDS\fR"
Timeout of image information displayed on the screen, 0 to always show, default is \fI5\fR.
.\" ----------------------------------------------------------------------------
.IP "\fBstatus_timeout\fR = \fISECONDS\fR"
Timeout of the status message displayed on the screen, default is \fI3\fR.
.\" ----------------------------------------------------------------------------
.SS "Text info: viewer"
The section \fB[info.viewer]\fR describes how to display image meta data (file
name, size, EXIF etc) in viewer mode.
Each key/value configures a set of fields and their format.
.IP "\fBtop_left\fR = \fILIST\fR"
Set the display scheme for the upper left corner of the window.
.IP "\fBtop_right\fR = \fILIST\fR"
Set the display scheme for the upper right corner of the window.
.IP "\fBbottom_left\fR = \fILIST\fR"
Set the display scheme for the lower left corner of the window.
.IP "\fBbottom_right\fR = \fILIST\fR"
Set the display scheme for the lower right corner of the window.
.PP
\fILIST\fR can contain any number of fields separated by commas.
Plus at the beginning of a field name adds the field title to the display.
Available fields:
.IP "\fIname\fR"
File name of the currently viewed/selected image.
.IP "\fIdir\fR"
Parent directory name the currently viewed/selected image.
.IP "\fIpath\fR"
Absolute path or special source string of the currently viewed/selected image.
.IP "\fIfilesize\fR"
File size in human readable format.
.IP "\fIformat\fR"
Brief image format description.
.IP "\fIimagesize\fR"
Size of the image (or its current frame) in pixels.
.IP "\fIexif\fR"
List of EXIF data.
.IP "\fIframe\fR"
Current and total number of frames.
.IP "\fIindex\fR"
Current and total index of image in the image list.
.IP "\fIscale\fR"
Current image scale in percent.
.IP "\fIstatus\fR"
Status message.
.IP "\fInone\fR"
Empty field (ignored).
.\" ----------------------------------------------------------------------------
.SS "Text info: gallery"
The section \fB[info.gallery]\fR describes how to display image meta data (file
name, size, EXIF etc) in gallery mode, same format as for viewer mode.
.\" ****************************************************************************
.\" Key bindings config section
.\" ****************************************************************************
.SS "Key bindings"
The key bindings are described in sections \fB[keys.viewer]\fR and \fB[keys.gallery]\fR.
Each line associates a key with a list of actions and optional parameters.
Actions are separated by semicolons.
One or more key modifiers (\fICtrl\fR, \fIAlt\fR, \fIShift\fR) can be specified
in the key name.
The key name can be obtained with the \fIxkbcli\fR tool:
`xkbcli interactive-wayland`.
.PP
Predefined names for mouse scroll:
.PP
.IP "\fIScrollUp\fR: Mouse wheel up;"
.IP "\fIScrollDown\fR: Mouse wheel down;"
.IP "\fIScrollLeft\fR: Mouse scroll left;"
.IP "\fIScrollRight\fR: Mouse scroll right."
.PP
.\" ----------------------------------------------------------------------------
.SS "Viewer mode actions"
.IP "\fBnone\fR: can be used for removing built-in action;"
.IP "\fBhelp\fR: show/hide help;"
.IP "\fBfirst_file\fR: jump to the first file;"
.IP "\fBlast_file\fR: jump to the last file;"
.IP "\fBprev_dir\fR: jump to previous directory;"
.IP "\fBnext_dir\fR: jump to next directory;"
.IP "\fBprev_file\fR: jump to previous file;"
.IP "\fBnext_file\fR: jump to next file;"
.IP "\fBrand_file\fR: jump to random file;"
.IP "\fBprev_frame\fR: show previous frame;"
.IP "\fBnext_frame\fR: show next frame;"
.IP "\fBskip_file\fR: skip the current file (remove from the image list);"
.IP "\fBanimation\fR: start/stop animation;"
.IP "\fBslideshow\fR: start/stop slideshow;"
.IP "\fBfullscreen\fR: switch full screen mode;"
.IP "\fBmode \fI[MODE]\fR\fR: switch between viewer and gallery;"
.IP "\fBstep_left\fR \fI[PERCENT]\fR: move viewport left, default is 10%;"
.IP "\fBstep_right\fR \fI[PERCENT]\fR: move viewport right, default is 10%;"
.IP "\fBstep_up\fR \fI[PERCENT]\fR: move viewport up, default is 10%;"
.IP "\fBstep_down\fR \fI[PERCENT]\fR: move viewport down, default is 10%;"
.IP "\fBzoom\fR \fI[SCALE]\fR: zoom in/out/fix, \fISCALE\fR is one of \fIviewer.scale\fR modes, or percent, e.g. \fI+10\fR;"
.IP "\fBscale\fR \fI[SCALE]\fR: set default/global scale, \fISCALE\fR is one of \fIviewer.scale\fR modes, cycles through available modes by default;"
.IP "\fBkeep_zoom\fR: toggle zoom keeping mode;"
.IP "\fBrotate_left\fR: rotate image anticlockwise;"
.IP "\fBrotate_right\fR: rotate image clockwise;"
.IP "\fBflip_vertical\fR: flip image vertically;"
.IP "\fBflip_horizontal\fR: flip image horizontally;"
.IP "\fBreload\fR: reset cache and reload current image;"
.IP "\fBantialiasing\fR \fI[MODE]\fR: switch antialiasing mode or set specified one (\fInext\fR/\fIprev\fR or mode name);"
.IP "\fBinfo\fR \fI[MODE]\fR: switch text info mode or set specified one (\fIoff\fR/\fIviewer\fR/\fIgallery\fR);"
.IP "\fBexec\fR \fICOMMAND\fR: execute an external command, use % to substitute the path to the current image, %% to escape %;"
.IP "\fBexport\fR \fIFILE\fR: export currently displayed image to PNG file;"
.IP "\fBstatus\fR \fITEXT\fR: print message in the status field;"
.IP "\fBexit\fR: exit the application."
.\" ----------------------------------------------------------------------------
.SS "Gallery mode actions"
.IP "\fBnone\fR: can be used for removing built-in action;"
.IP "\fBhelp\fR: show/hide help;"
.IP "\fBfirst_file\fR: jump to the first file;"
.IP "\fBlast_file\fR: jump to the last file;"
.IP "\fBprev_file\fR: select previous file;"
.IP "\fBnext_file\fR: select next file;"
.IP "\fBstep_left\fR: select previous image;"
.IP "\fBstep_right\fR: select next image;"
.IP "\fBstep_up\fR: select image above;"
.IP "\fBstep_down\fR: select image below;"
.IP "\fBpage_up\fR: scroll page up;"
.IP "\fBpage_down\fR: scroll page down;"
.IP "\fBskip_file\fR: skip the current file (remove from the image list);"
.IP "\fBfullscreen\fR: switch full screen mode;"
.IP "\fBmode\fR: switch between viewer and gallery;"
.IP "\fBreload\fR: reset cache and reload current image;"
.IP "\fBantialiasing\fR \fI[MODE]\fR: switch antialiasing mode or set specified one (\fInext\fR/\fIprev\fR or mode name);"
.IP "\fBinfo\fR \fI[MODE]\fR: switch text info mode or set specified one (\fIoff\fR/\fIviewer\fR/\fIgallery\fR);"
.IP "\fBexec\fR \fICOMMAND\fR: execute an external command, use % to substitute the path to the current image, %% to escape %;"
.IP "\fBstatus\fR \fITEXT\fR: print message in the status field;"
.IP "\fBexit\fR: exit the application."
.\" ****************************************************************************
.\" Example
.\" ****************************************************************************
.SH EXAMPLES
.EX
# comment
[list]
order = random
[font]
size = 16
[keys]
Ctrl+Alt+e = exec echo "%" > mylist.txt
.EE
.PP
See `/usr/share/swayimg/swayimgrc` for full example.
.\" ****************************************************************************
.\" Cross links
.\" ****************************************************************************
.SH SEE ALSO
swayimg(1)
.\" ****************************************************************************
.\" Home page
.\" ****************************************************************************
.SH BUGS
For suggestions, comments, bug reports etc. visit the
.UR https://github.com/artemsen/swayimg
project homepage
.UE .
