name: Alpine
on: [push, pull_request]

jobs:
  i386:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: /tmp/build
      INSTALL_DIR: /tmp/install

    steps:
    - name: Check out source code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Get app version
      run: echo "VERSION=$(git describe --tags --long --always | sed 's/^v//;s/-/./')" >> $GITHUB_OUTPUT
      id: version

    - name: Build docker image
      run: docker build --tag=swayimg --platform=linux/i386 --file=.github/workflows/Dockerfile.Alpine .

    - name: Run docker container
      run: >
        docker run --tty --detach
        --name=swayimg
        --volume=$PWD:$PWD:ro
        --workdir=$PWD
        swayimg

    - name: Setup
      run: >
        docker exec swayimg
        meson setup
        --auto-features=enabled
        --prefix=/usr
        --werror
        -D tests=enabled
        -D version=${{steps.version.outputs.VERSION}}
        ${{ env.BUILD_DIR }}

    - name: Compile
      run: >
        docker exec swayimg
        meson compile -C ${{ env.BUILD_DIR }}

    - name: Run unit tests
      run: >
        docker exec swayimg
        meson test --verbose -C ${{ env.BUILD_DIR }}

    - name: Install
      run: >
        docker exec swayimg
        env DESTDIR=${{ env.INSTALL_DIR }}
        meson install -C ${{ env.BUILD_DIR }}

    - name: Run/version
      run: >
        docker exec swayimg
        ${{ env.INSTALL_DIR }}/usr/bin/swayimg --version

    - name: Run/help
      run: >
        docker exec swayimg
        ${{ env.INSTALL_DIR }}/usr/bin/swayimg --help
