name: Code format
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: /tmp/build

    steps:
    - name: Check out source code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Build docker image
      run: docker build --tag=swayimg --file=.github/workflows/Dockerfile.Arch .

    - name: Run docker container
      run: >
        docker run --tty --detach
        --name=swayimg
        --volume=$PWD:$PWD:ro
        --workdir=$PWD
        swayimg

    - name: Check source code format
      run: >
        docker exec swayimg
        clang-format --Werror --dry-run src/*.cpp src/*.hpp src/formats/* test/*.cpp

    - name: Check Lua doc
      run: |
        docker exec swayimg extra/lua2md.py extra/swayimg.lua > /tmp/CONFIG.md
        cmp /tmp/CONFIG.md CONFIG.md || { echo "CONFIG.md doesn't match extra/swayimg.lua"; exit 1; }

    - name: Check man doc
      run: |
        docker exec swayimg extra/md2man.py USAGE.md > /tmp/swayimg.1
        cmp /tmp/swayimg.1 extra/swayimg.1 || { echo "extra/swayimg.1 doesn't match USAGE.md"; exit 1; }
